swagger: '2.0'
info:
  description: >-
    ares http api doc
  version: 0.0.1
  title: ares http api doc
basePath: /
tags:
  - name: Message Verification
  - name: User Base
  - name: User Finance
paths:
  "/api/message_verification/send":
    post:
      tags:
        - Message Verification
      summary: 请求发送手机验证码
      description: 请求发送手机验证码
      operationId: message_verification_send
      consumes:
        - multipart/form-data
      parameters:
        - name: phone
          in: formData
          type: integer
          description: 手机号
          required: true
      produces:
        - application/json
      responses:
        200:
          description: |
            发送成功
            ```json
              {
                status: 200
              }
            ```
          schema:
            type: object
            properties:
              status:
                type: integer
                enum:
                  - 200
  "/api/message_verification/verify":
    post:
      tags:
        - Message Verification
      summary: 检查手机验证码是否正确
      description: 检查提交的手机验证码是否和该手机最后收到的手机验证码相匹配
      operationId: message_verification_verify
      consumes:
        - multipart/form-data
      parameters:
        - name: phone
          in: formData
          type: integer
          description: 手机号
          required: true
        - name: verify_code
          in: formData
          type: string
          description: 手机验证码
          required: true
      produces:
        - application/json
      responses:
        200:
          description: |
            验证成功
            ```json
              {
                status: 200
              }
            ```
          schema:
            type: object
            properties:
              status:
                type: integer
                enum:
                  - 200
        422:
          description: |
            验证失败
            ```json
              {
                errors: {
                  verify_code: "验证码错误"
                }
              }
            ```
          schema:
            type: object
            properties:
              errors:
                type: object
            
  "/api/auth/sign_up":
    post:
      tags:
        - User Base
      summary: 提交用户注册信息
      description: 提交用户注册信息
      operationId: auth_sign_up
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: phone
          in: formData
          type: integer
          description: 手机号
          required: true
        - name: name
          in: formData
          type: string
          description: 姓名
          required: true
        - name: card_type
          description: 证件类型
          required: true
          in: formData
          type: string
          enum:
            - 身份证
            - 军官证
        - name: card_number
          in: formData
          type: integer
          description: 证件号码
          required: true
        - name: password
          in: formData
          type: string
          format: password
          description: 密码
          required: true

        - name: invitation_code
          in: formData
          type: string
          description: 邀请码
      responses:
        '200':
          description: |
            注册成功
            ```json
              {
                status: 200
              }
            ```
        '422':
          description: |
            注册失败
            ```json
              // 有疑惑
            ```
          schema:
            type: object
            properties:
              errors:
                type: object
  "/api/auth/sign_in":
    post:
      tags:
        - User Base
      summary: 用户登录
      description: 用户登录
      operationId: auth_sign_in
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: phone
          in: formData
          type: string
          description: 手机号
          required: true
        - name: password
          in: formData
          type: string
          format: password
          description: 密码
          required: true
      responses:
        '200':
          description: |
            登录成功
            ```json
              {
                status: 200
              }
            ```
          headers:
            "Set-Cookie":
              description: "cookie 信息"
              type: string
          schema:
            type: object
        '411':
          description: |
            登录失败
            ```json
              {
                status: 411,
                message: "用户不存在"
              }
            ```
            ```json
              {
                status: 411,
                message: "用户名或密码不正确"
              }
            ```
          schema:
            type: object
            properties:
              errors:
                type: object
  "/api/user_finance/info":
    get:
      tags:
        - User Finance
      summary: 获取当前用户金融信息
      description: 获取当前用户金融信息
      operationId: user_finance_info
      produces:
        - application/json
      parameters:
        - name: Cookie
          in: header
          type: string
          description: Cookie 信息
          required: true
      responses:
        '200':
          description: |
            成功获取当前用户金融信息
            ```json
              {
                
                  bank_card_count: 2,
                  balance: 1000
              }
            ```
          schema:
            type: object
            properties:
              bank_card_count:
                type: integer  
              balance:
                type: string 
        "411":
          description: |
            没有登录
          schema:
            type: string

definitions:
  User:
    type: object
    properties:
      phone:
        type: integer  
      name:
        type: string  
      card_type:
        type: string
      card_number:
        type: integer  